import type { ModelConfig } from "../types"

// Lista modeli DashScope, które będą dostępne w Twojej aplikacji.
// Dodaj tutaj tyle modeli, ile chcesz obsługiwać – poniżej przykładowe.

export const dashscopeModels: ModelConfig[] = [
  {
    id: "dashscope-qwen-turbo",
    name: "Qwen Turbo",
    provider: "dashscope",
    providerId: "dashscope",
    modelFamily: "Qwen",
    description: "Szybki i wydajny model Qwen Turbo od DashScope.",
    tags: ["fast", "cheap"],
    contextWindow: 128000,
    inputCost: 0.0001,
    outputCost: 0.0002,
    priceUnit: "per 1M tokens",
    speed: "Fast",
    intelligence: "Medium",
    website: "https://dashscope.aliyun.com/",
    apiDocs: "https://dashscope.aliyun.com/api",
    modelPage: "https://dashscope.aliyun.com/models/qwen-turbo",
    releasedAt: "2024-04-01",
    apiSdk: undefined,
  },
  {
    id: "dashscope-qwen-plus-latest",
    name: "Qwen Plus",
    provider: "dashscope",
    providerId: "dashscope",
    modelFamily: "Qwen",
    description: "Model Qwen Plus DashScope – wyższa jakość odpowiedzi.",
    tags: ["accurate"],
    contextWindow: 128000,
    inputCost: 0.0002,
    outputCost: 0.0004,
    priceUnit: "per 1M tokens",
    speed: "Medium",
    intelligence: "High",
    website: "https://dashscope.aliyun.com/",
    apiDocs: "https://dashscope.aliyun.com/api",
    modelPage: "https://dashscope.aliyun.com/models/qwen-plus",
    releasedAt: "2024-05-01",
    apiSdk: undefined,
  },
  {
    id: "dashscope-qwen3-30b-a3b",
    name: "Qwen3-30B-A3B",
    provider: "dashscope",
    providerId: "dashscope",
    modelFamily: "Qwen",
    description: "Qwen3-30B-A3B – zaawansowany model DashScope.",
    tags: ["OSS", "accurate"],
    contextWindow: 128000,
    inputCost: 0.00025,
    outputCost: 0.0005,
    priceUnit: "per 1M tokens",
    speed: "Medium",
    intelligence: "High",
    website: "https://dashscope.aliyun.com/",
    apiDocs: "https://dashscope.aliyun.com/api",
    modelPage: "https://dashscope.aliyun.com/models/qwen3-30b-a3b",
    releasedAt: "2024-06-01",
    apiSdk: undefined,
  },
  {
    id: "dashscope-qwq-plus",
    name: "QWQ Plus",
    provider: "dashscope",
    providerId: "dashscope",
    modelFamily: "Qwen",
    description: "QWQ Plus – model DashScope do zadań specjalnych.",
    tags: ["special"],
    contextWindow: 128000,
    inputCost: 0.0003,
    outputCost: 0.0006,
    priceUnit: "per 1M tokens",
    speed: "Medium",
    intelligence: "High",
    website: "https://dashscope.aliyun.com/",
    apiDocs: "https://dashscope.aliyun.com/api",
    modelPage: "https://dashscope.aliyun.com/models/qwq-plus",
    releasedAt: "2024-07-01",
    apiSdk: undefined,
  },
  {
    id: "dashscope-qwen3-32b",
    name: "Qwen-3-32B",
    provider: "dashscope",
    providerId: "dashscope",
    modelFamily: "Qwen",
    description: "Qwen-3-32B – model DashScope o dużych możliwościach.",
    tags: ["big", "powerful"],
    contextWindow: 128000,
    inputCost: 0.0004,
    outputCost: 0.0008,
    priceUnit: "per 1M tokens",
    speed: "Slow",
    intelligence: "High",
    website: "https://dashscope.aliyun.com/",
    apiDocs: "https://dashscope.aliyun.com/api",
    modelPage: "https://dashscope.aliyun.com/models/qwen3-32b",
    releasedAt: "2024-08-01",
    apiSdk: undefined,
  }
]
